COMP: Update dependencies with npm update
Addresses:

```
success Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 0.032s - 6/6 186.81/s

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

No element indexed by 0

File: node_modules/gatsby-plugin-image/dist/gatsby-image.browser.module.js

failed Building development bundle - 9.458s
ERROR in ./node_modules/gatsby-plugin-image/dist/gatsby-image.browser.module.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: No element indexed by 0
    at ArraySet.at (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/array-set.js:88:11)
    at Array.<anonymous> (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:357:42)
    at mapping_callback (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:64:52)
    at null.<anonymous> (wasm://wasm/0002f8d6:1:15533)
    at /home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:370:30
    at Object.withMappingCallback (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.eachMapping (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:354:16)
    at Function.fromStringWithSourceMap (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-node.js:87:24)
    at /home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:79:33
    at Function.with (/home/matt/src/insightsoftwareconsortium.org/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:70:20)
 @ ./src/components/image.js 8:0-50 24:46-57
 @ ./src/pages/index.js?export=head 8:0-40 63:38-43
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 87:11-89:5
 @ ./.cache/app.js 18:0-52 31:87-35:1 34:29-42 37:27-40 31:0-35:2

develop compiled with 1 error

```